<!--
yyssssoooooo++++++///////:::::::-----//:://+++oo++++++//oyhy+/::-:///+o++/+//:-.....----:::::://///+
ssssooooo++++++////////:::::-------::+ssoosyyyyyyysyyyyyyhhyysooosyyys+:-............------::::::://
sssooo+++++++//////::::::::::::::://+sysssyyyhyhhhhyhhhhhdddhhhhhhhyyss/:-..............------::::::
sooooo++++///////::::::::::::/+//+yyyyysyyyhyyhdhdddddddddddddddddhhhhys+::-..............-----:::::
oooo+++++///////:::::::::--:/osssyyyhyyyyyhddddddddhso+/:::::/+syddddhhhyso+--..............-----:::
oo+++++////////:::::::::::++yysyyyhyhyyyyhhddddddy+-......`......-/oydddhhyso/-..............-------
oo++++/////////:::::::::/+syyssyyyyyyyhhdhddddddy+-......```........-:shddhhys/--...............----
oo+++////////::::::///+oyyyyhdhyyhyhhhhdddddmmds/--..--::---..``.......-ohdhhhyo+/-................-
o+++///////::::::::+ssyyyshmdhhhhdhhdhddddddmmho:.:/oossyyyyso/......----:shhhhhs+/:-..............-
+++////////::::+o+shhhysydddddhdhyyhhhdddddmmds/-+o++//::+yhhhy/-.`....---:ydddhhyo/:--.............
+/////::::///++shhhhyyyhdddmmmmhhhhhhhhdddmmhs/:/+sssssssoyhhhyo:...--...--/dddhhhhys+:...`.........
+////::::::/osyhhddhshdmddhddhyyyhhhdhddmmmy/:---://+oosshhyhyo/-.-+o++/:-.-yddddhddhs:-..``........
+////::::::/oyhddddyydmdhhddddhsyhhhhhddmdo:-.......:ossoosoo+/-.`.yhhhhys/:oddddhdddho/---.........
/////:::::/+yhdddhyhdmmhddddddysyhhhddddd+-.-.......`..-:::::...```/hso++syyoddddhhddhyo+.-.........
///:::::/oshdddhhyydmmmmhddddhsyhhhhdddhh///-........--::--..--.....+soo/:+yyhdddhhdddho:-..........
//:::://+yhyyhhhhydmmmmhhddddyssshhdmmddd+o:--:////+osss+//+shys++/::++oyy++shddddyhddhs:-..........
//:::::/+yyhhddyhmmmmmdsmdsyhyssshhdmmmdho+-//++oooo+/:--:/ooyyyyyyyo+so+yh+shmddhyddhhy+-..........
/::::::/shyhddhydmmmmmmsh+yhhyssshddmmmdyo:++///ooo+//:///++osssssydh/:://sosddmdhydhhyyo/..........
::::::/+shhhdmsdmmmmmmmd/oo+oyoosddmmmmds+/+/::/+shssoosoooo+/+osssso+....-/hmmmddddhyyhs:..........
/:::/+syhhddmmshmmmmmmmmh+/+yssoshdmmmmds+o+:::/+yddyoo+++shyyo+++yo/o/....+dmmmdhhddddhs:..........
:::/+yshhhddmdydmmmmmmmmmmmyyyoshddmmmmdo+o+::///+yo+-..-.--:oyhysoo/++---.ommmmdhdddddhy/-.........
::::+syhhddmmhdmmmmmmmmmmyhydosyhdmmmmmho+o+:/+:::-:+sssyoo-.../ydyso++:::-hmmmmdddddddho/-.........
::::+yhhddmmmhmmmmmmmmmmmmmdysyhdmmmmmmho+oo++o::--.--:/oydddo-./ddhys+oo/+mmmmdhdddddhh+:..........
:::/ydhddmmmmhdmmmmmmmmmmmmdshdmmmmmmmmhs+++++o:::---:/o+:-:+yo-hmhhysssssdmmmmhhddddddho/..........
::/+ydhddmmmmhmmmmmmmmmmmmyhyhdmmmmmmmmdyo+///::-///::/osssooooossyhysyhdmmmmmdddddddddho+-.........
//+syhhddmmmmddmmmdmmmmmmmsshdmmmmmmmmmmhsoo++::---://+ossooosoo/oysyhhdmmmmmdhmmddddhdyo:-.........
/oshddddmmmmmydmmmdmmmmmmmyyydmmmmddmmmmmdhysyo+/:-----/++ooooo+osyyyhdmmmmmmddmmdddhdhs/-.........`
+sdmhhhddmmmmyhmmmdmmmmmmdyyddmmmdmmmmmmdddhhhhysssoso+:::/+/++syssshmmmmmmmmhmmmdddhdds-...........
odmmyhdddmmmmhdmmsmmmmmmmysyydmmmdddmmmmddddddhhyhyhhhhyys++//syooshmmmmmmmmmhmmdhhdddho-...........
hmmhhhddmmmmmmmmyommmmmmhyyyhdmmmdhddmmmmdhdmmdhhhhhhdddhhhyohhyssddmmmmmmmmdhmdyyyyhhs-............
mmmhhhdmmmmmmmmmmydhdmmmhhhshdmmmddddmmmmhdhdmmmdmmdhhhhdddhdhhhhdmmmmmmmmmmmhmhyyyyss:.............
mmhhhddmdmmmmmmydmdyhdmdymdoydmmmdddhmmmdhhddmmmmmmmdddddddddddhdmmmmmmmmmmmmmdhhsysyo-.............
mdhhdmmmmmmmmmd/dNmsyyyhhhhoydmmmhdh+ymmmddddmmmmmmmmmdmmddmmmdddmmmmmmmmmmmmdhsssyyhs/.............
msmdmdmmmmmmmmmyNmdoosohdysoydmmdhdy/shdmdddmmmmmmmmmddmdmmmmmddmmmmmmmmmmhddysosssyhhy/-...........
hhmdddddmmmmmmmdhyssso+hdo+shdmdhdd+/osyhhhdddmmmmmmmmmmdmmmdddsmmmmmmmmmdhdyooysyyshhyo+:..........
ymNmdmddddmmmmmdysooo//hdo+shmdshmy//+syyyysyhdmmmmmmmmmddhhdh+:dmmmmmmmdddho+ysyhyshhyss+:.........
dNNNhhydddmdhdmdyso+/::ydooshmyyddo+/+ssyyyysyhhdmmmmmdhhyyhh/./mmmmmmddddyssyyyyhyydddhsoo/........
mNNNhhymmmmmhhmdsso/:::smo+sdyyddo+//+sssssssshdddddhhyyhyhs:.-hmmmdddddhsoodhysyysddddhhyso/-......
NNNNhhhdmNNmddmdoso/:::sdooyhsydoo+//+ssssooooyyyyyyyyyhhs+-.-smmdhddhyss+oddhyshyydddddddhy++:-....
mNNNyhddNNmdddmmso+/::-/yyossydho+++/oosooooosssssyyyyyo/-../oyhdhdhsyysoohmdysyysymdddddyyooyo/-...
NNNdsyhmNNddddmNyo+::+o/ohsyyhdhoooo+osooooooossssyyyo++-..ohyyyyyyydyooohmmdsyyysddddhyosoyyyhy/-..
NNNhshdmNNmdmmmNy++/hmmssyyhhymy++ooossoooooossyyso+oydmo-/sssyyyhdmsssshmmdhssss+syyyoo+yyshdddyo/-
NNNyyydmNNmddmNNy+ohdyhhdhyydhdo++ooossooooossys/://+oyhd/sohhsydmmyssoshmmhysyys..oy++ssdysyhdddhs+
NNNssydmNNmddmNNhohhshmmmdysydhs+oosossoooosy+//::///+oyyssydssyhmmssosymmdhssyh+-/hso+hdmyssdmddhyo
NNNsshdmNNmddmNNmdhyhmmhhddodhhyoosssssoosoyo:///////+ohysyhdoohmmmddsydmdyhyhhy:-ohso+ydhysshmmdhs+
NNmssydNNmdhdmmmyhhdmhyhhmm+ddhysssyysssooy+:///////++sdyssdyssdmmdhyyhmmdhyhyho--:hysooooyysyddmhso
NNmsyydNNmddmNdyhdmhsoyhhddomhhyssyyyssooy+:////:://++hyyshdoosmdhyssdmmdyyyydy---:ydyso//+hyoosddy+
NNdsyhmNNmdmmdyydmd+/ohhdmyddyssssyyyssss+://////:///sysyydhs+ydyysydNmhyyyhhy----:+hyys:-:+ys//hdyo
NNhshdmNNNmNmshdmmd++yyhddmmyssssooo+++s///////::///+y+hhdmy+++yyyhmdhssyhhddo----::hyss/--/ys+:shyo
NNhyhdmNNNNmydNNNhh+oydmhddyssssoooooos/////:::/:://s+yshhssooyyoymmysoyydmmho///::/shyo/-:+hsy:+yso
NNhhhdmNNNmhmNNNdoooohddhodysooooooooso///::///:://o+s++ssosyyshhhyyyhhhhdmmhs+//////ydy++//yys+/+++
-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Warisan | @yield('title')</title>
    <meta name="description" content="{{ 'meta_description' }}">
    <meta name="keywords" content="{{ 'meta_keywords' }}">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <link rel="shortcut icon" href="http://warisan.com/images/icon.jpg">
    <link rel="icon" href="http://warisan.com/images/icon.jpg">

    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,700,600italic,700italic,800italic,800' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/responsive.css') }}">

    <!--   If is homepage     -->
    @if(Request::path() == '/')
    <link rel="stylesheet" href="{{ asset('assets/css/main-menu-home.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/revolution-slider/settings.css') }}" media="screen"/>

    @elseif(Request::path() == 'contact')
    <!--   If is contact page     -->
    <link rel="stylesheet" href="{{ asset('assets/css/main-menu-home.css') }}">

    @else
    <!--   If other pages     -->
    <link rel="stylesheet" href="{{ asset('assets/css/main-menu.css') }}">
    @endif

    <link rel="stylesheet" href="{{ asset('assets/css/smart-forms.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/font-awesome.css') }}">

    <!-- JQUERY LIB -->
    <script>var baseUrl = '{{ env('BASE_URL', 'matter.io') }}/';</script>
</head>
