<!--
yyssssoooooo++++++///////:::::::-----//:://+++oo++++++//oyhy+/::-:///+o++/+//:-.....----:::::://///+
ssssooooo++++++////////:::::-------::+ssoosyyyyyyysyyyyyyhhyysooosyyys+:-............------::::::://
sssooo+++++++//////::::::::::::::://+sysssyyyhyhhhhyhhhhhdddhhhhhhhyyss/:-..............------::::::
sooooo++++///////::::::::::::/+//+yyyyysyyyhyyhdhdddddddddddddddddhhhhys+::-..............-----:::::
oooo+++++///////:::::::::--:/osssyyyhyyyyyhddddddddhso+/:::::/+syddddhhhyso+--..............-----:::
oo+++++////////:::::::::::++yysyyyhyhyyyyhhddddddy+-......`......-/oydddhhyso/-..............-------
oo++++/////////:::::::::/+syyssyyyyyyyhhdhddddddy+-......```........-:shddhhys/--...............----
oo+++////////::::::///+oyyyyhdhyyhyhhhhdddddmmds/--..--::---..``.......-ohdhhhyo+/-................-
o+++///////::::::::+ssyyyshmdhhhhdhhdhddddddmmho:.:/oossyyyyso/......----:shhhhhs+/:-..............-
+++////////::::+o+shhhysydddddhdhyyhhhdddddmmds/-+o++//::+yhhhy/-.`....---:ydddhhyo/:--.............
+/////::::///++shhhhyyyhdddmmmmhhhhhhhhdddmmhs/:/+sssssssoyhhhyo:...--...--/dddhhhhys+:...`.........
+////::::::/osyhhddhshdmddhddhyyyhhhdhddmmmy/:---://+oosshhyhyo/-.-+o++/:-.-yddddhddhs:-..``........
+////::::::/oyhddddyydmdhhddddhsyhhhhhddmdo:-.......:ossoosoo+/-.`.yhhhhys/:oddddhdddho/---.........
/////:::::/+yhdddhyhdmmhddddddysyhhhddddd+-.-.......`..-:::::...```/hso++syyoddddhhddhyo+.-.........
///:::::/oshdddhhyydmmmmhddddhsyhhhhdddhh///-........--::--..--.....+soo/:+yyhdddhhdddho:-..........
//:::://+yhyyhhhhydmmmmhhddddyssshhdmmddd+o:--:////+osss+//+shys++/::++oyy++shddddyhddhs:-..........
//:::::/+yyhhddyhmmmmmdsmdsyhyssshhdmmmdho+-//++oooo+/:--:/ooyyyyyyyo+so+yh+shmddhyddhhy+-..........
/::::::/shyhddhydmmmmmmsh+yhhyssshddmmmdyo:++///ooo+//:///++osssssydh/:://sosddmdhydhhyyo/..........
::::::/+shhhdmsdmmmmmmmd/oo+oyoosddmmmmds+/+/::/+shssoosoooo+/+osssso+....-/hmmmddddhyyhs:..........
/:::/+syhhddmmshmmmmmmmmh+/+yssoshdmmmmds+o+:::/+yddyoo+++shyyo+++yo/o/....+dmmmdhhddddhs:..........
:::/+yshhhddmdydmmmmmmmmmmmyyyoshddmmmmdo+o+::///+yo+-..-.--:oyhysoo/++---.ommmmdhdddddhy/-.........
::::+syhhddmmhdmmmmmmmmmmyhydosyhdmmmmmho+o+:/+:::-:+sssyoo-.../ydyso++:::-hmmmmdddddddho/-.........
::::+yhhddmmmhmmmmmmmmmmmmmdysyhdmmmmmmho+oo++o::--.--:/oydddo-./ddhys+oo/+mmmmdhdddddhh+:..........
:::/ydhddmmmmhdmmmmmmmmmmmmdshdmmmmmmmmhs+++++o:::---:/o+:-:+yo-hmhhysssssdmmmmhhddddddho/..........
::/+ydhddmmmmhmmmmmmmmmmmmyhyhdmmmmmmmmdyo+///::-///::/osssooooossyhysyhdmmmmmdddddddddho+-.........
//+syhhddmmmmddmmmdmmmmmmmsshdmmmmmmmmmmhsoo++::---://+ossooosoo/oysyhhdmmmmmdhmmddddhdyo:-.........
/oshddddmmmmmydmmmdmmmmmmmyyydmmmmddmmmmmdhysyo+/:-----/++ooooo+osyyyhdmmmmmmddmmdddhdhs/-.........`
+sdmhhhddmmmmyhmmmdmmmmmmdyyddmmmdmmmmmmdddhhhhysssoso+:::/+/++syssshmmmmmmmmhmmmdddhdds-...........
odmmyhdddmmmmhdmmsmmmmmmmysyydmmmdddmmmmddddddhhyhyhhhhyys++//syooshmmmmmmmmmhmmdhhdddho-...........
hmmhhhddmmmmmmmmyommmmmmhyyyhdmmmdhddmmmmdhdmmdhhhhhhdddhhhyohhyssddmmmmmmmmdhmdyyyyhhs-............
mmmhhhdmmmmmmmmmmydhdmmmhhhshdmmmddddmmmmhdhdmmmdmmdhhhhdddhdhhhhdmmmmmmmmmmmhmhyyyyss:.............
mmhhhddmdmmmmmmydmdyhdmdymdoydmmmdddhmmmdhhddmmmmmmmdddddddddddhdmmmmmmmmmmmmmdhhsysyo-.............
mdhhdmmmmmmmmmd/dNmsyyyhhhhoydmmmhdh+ymmmddddmmmmmmmmmdmmddmmmdddmmmmmmmmmmmmdhsssyyhs/.............
msmdmdmmmmmmmmmyNmdoosohdysoydmmdhdy/shdmdddmmmmmmmmmddmdmmmmmddmmmmmmmmmmhddysosssyhhy/-...........
hhmdddddmmmmmmmdhyssso+hdo+shdmdhdd+/osyhhhdddmmmmmmmmmmdmmmdddsmmmmmmmmmdhdyooysyyshhyo+:..........
ymNmdmddddmmmmmdysooo//hdo+shmdshmy//+syyyysyhdmmmmmmmmmddhhdh+:dmmmmmmmdddho+ysyhyshhyss+:.........
dNNNhhydddmdhdmdyso+/::ydooshmyyddo+/+ssyyyysyhhdmmmmmdhhyyhh/./mmmmmmddddyssyyyyhyydddhsoo/........
mNNNhhymmmmmhhmdsso/:::smo+sdyyddo+//+sssssssshdddddhhyyhyhs:.-hmmmdddddhsoodhysyysddddhhyso/-......
NNNNhhhdmNNmddmdoso/:::sdooyhsydoo+//+ssssooooyyyyyyyyyhhs+-.-smmdhddhyss+oddhyshyydddddddhy++:-....
mNNNyhddNNmdddmmso+/::-/yyossydho+++/oosooooosssssyyyyyo/-../oyhdhdhsyysoohmdysyysymdddddyyooyo/-...
NNNdsyhmNNddddmNyo+::+o/ohsyyhdhoooo+osooooooossssyyyo++-..ohyyyyyyydyooohmmdsyyysddddhyosoyyyhy/-..
NNNhshdmNNmdmmmNy++/hmmssyyhhymy++ooossoooooossyyso+oydmo-/sssyyyhdmsssshmmdhssss+syyyoo+yyshdddyo/-
NNNyyydmNNmddmNNy+ohdyhhdhyydhdo++ooossooooossys/://+oyhd/sohhsydmmyssoshmmhysyys..oy++ssdysyhdddhs+
NNNssydmNNmddmNNhohhshmmmdysydhs+oosossoooosy+//::///+oyyssydssyhmmssosymmdhssyh+-/hso+hdmyssdmddhyo
NNNsshdmNNmddmNNmdhyhmmhhddodhhyoosssssoosoyo:///////+ohysyhdoohmmmddsydmdyhyhhy:-ohso+ydhysshmmdhs+
NNmssydNNmdhdmmmyhhdmhyhhmm+ddhysssyysssooy+:///////++sdyssdyssdmmdhyyhmmdhyhyho--:hysooooyysyddmhso
NNmsyydNNmddmNdyhdmhsoyhhddomhhyssyyyssooy+:////:://++hyyshdoosmdhyssdmmdyyyydy---:ydyso//+hyoosddy+
NNdsyhmNNmdmmdyydmd+/ohhdmyddyssssyyyssss+://////:///sysyydhs+ydyysydNmhyyyhhy----:+hyys:-:+ys//hdyo
NNhshdmNNNmNmshdmmd++yyhddmmyssssooo+++s///////::///+y+hhdmy+++yyyhmdhssyhhddo----::hyss/--/ys+:shyo
NNhyhdmNNNNmydNNNhh+oydmhddyssssoooooos/////:::/:://s+yshhssooyyoymmysoyydmmho///::/shyo/-:+hsy:+yso
NNhhhdmNNNmhmNNNdoooohddhodysooooooooso///::///:://o+s++ssosyyshhhyyyhhhhdmmhs+//////ydy++//yys+/+++
-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{{ env('APP_NAME', 'Matter') }}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/>
    <link rel="apple-touch-icon" href="{{ asset('assets/img/common/apple-touch-icon.png') }}">

    <link rel="stylesheet" href="{{ asset('assets/css/normalize.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/styles.css') }}">

    <link href='https://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
